runtime: python39

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "myapp.settings"
  SECRET_KEY: "your-secret-key"

automatic_scaling:
  min_instances: 1
  max_instances: 5

resources:
  cpu: 1
  memory_gb: 16
